-- Minimal HSQLDB schema for persistence tests.
-- PostgreSQL-only full text search objects, GIN indexes, triggers, functions, and seed data are intentionally omitted.

DROP SCHEMA PUBLIC CASCADE;

-- HSQLDB does not expose PostgreSQL BTRIM; DAOs use it for email normalization.
CREATE FUNCTION BTRIM(p_value VARCHAR(32672))
RETURNS VARCHAR(32672)
RETURN TRIM(BOTH FROM p_value);

CREATE TABLE users (
    user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL DEFAULT 'user',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_follows (
    follower_id INTEGER   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    followed_id INTEGER   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_follows PRIMARY KEY (follower_id, followed_id),
    CONSTRAINT chk_user_follows_no_self_follow CHECK (follower_id <> followed_id)
);

CREATE TABLE brands (
    brand_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(80) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE body_types (
    body_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL UNIQUE,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cars (
    car_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id         BIGINT       NOT NULL REFERENCES brands(brand_id) ON DELETE RESTRICT,
    model            VARCHAR(120) NOT NULL,
    body_type_id     SMALLINT     NOT NULL REFERENCES body_types(body_type_id) ON DELETE RESTRICT,
    year             INTEGER,
    description      LONGVARCHAR,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fuel_type        VARCHAR(20),
    horsepower       INTEGER,
    airbag_count     INTEGER,
    transmission     VARCHAR(20),
    fuel_consumption NUMERIC(4,1),
    max_speed_kmh    INTEGER,
    price_usd        NUMERIC(12,2),
    CONSTRAINT uq_cars_brand_model_body_type_year UNIQUE (brand_id, model, body_type_id, year),
    CONSTRAINT chk_cars_year CHECK (year IS NULL OR year BETWEEN 1950 AND 2100),
    CONSTRAINT chk_cars_fuel_type CHECK (fuel_type IS NULL OR fuel_type IN ('combustion', 'hybrid', 'electric')),
    CONSTRAINT chk_cars_transmission CHECK (transmission IS NULL OR transmission IN ('manual', 'automatic'))
);

CREATE TABLE car_favorites (
    user_id    INTEGER   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    car_id     BIGINT    NOT NULL REFERENCES cars(car_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_car_favorites PRIMARY KEY (user_id, car_id)
);

CREATE TABLE car_images (
    image_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id        BIGINT       NOT NULL REFERENCES cars(car_id) ON DELETE CASCADE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    content_type  VARCHAR(100) NOT NULL,
    image_data    BYTEA        NOT NULL,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_car_images_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_car_images_car_order UNIQUE (car_id, display_order)
);

CREATE TABLE car_requests (
    car_request_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
    submitter_email      VARCHAR(100),
    brand_id             BIGINT       NOT NULL REFERENCES brands(brand_id) ON DELETE RESTRICT,
    body_type_id         SMALLINT     NOT NULL REFERENCES body_types(body_type_id) ON DELETE RESTRICT,
    year                 INTEGER,
    model                VARCHAR(120) NOT NULL,
    description          LONGVARCHAR  NOT NULL,
    image_content_type   VARCHAR(100),
    image_data           BYTEA,
    status               VARCHAR(20)  NOT NULL DEFAULT 'pending',
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fuel_type            VARCHAR(20),
    horsepower           INTEGER,
    airbag_count         INTEGER,
    transmission         VARCHAR(20),
    fuel_consumption     NUMERIC(4,1),
    max_speed_kmh        INTEGER,
    price_usd            NUMERIC(12,2),
    CONSTRAINT chk_car_requests_submitter_identity CHECK (submitted_by_user_id IS NOT NULL OR submitter_email IS NOT NULL),
    CONSTRAINT chk_car_requests_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT chk_car_requests_image_payload CHECK (
        (image_content_type IS NULL AND image_data IS NULL)
        OR (image_content_type IS NOT NULL AND image_data IS NOT NULL)
    )
);

CREATE TABLE car_request_images (
    image_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_request_id BIGINT       NOT NULL REFERENCES car_requests(car_request_id) ON DELETE CASCADE,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    content_type   VARCHAR(100) NOT NULL,
    image_data     BYTEA        NOT NULL,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_car_request_images_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_car_request_images_request_order UNIQUE (car_request_id, display_order)
);

CREATE TABLE reviews (
    review_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER REFERENCES users(user_id),
    reviewer_email   VARCHAR(100),
    car_id           BIGINT       NOT NULL REFERENCES cars(car_id) ON DELETE CASCADE,
    rating           NUMERIC(3,1) NOT NULL CHECK (rating BETWEEN 0.0 AND 5.0),
    title            VARCHAR(200) NOT NULL,
    body             LONGVARCHAR  NOT NULL,
    ownership_status VARCHAR(20),
    model_year       INTEGER,
    mileage_km       INTEGER,
    would_recommend  BOOLEAN,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reviews_reviewer_identity CHECK (user_id IS NOT NULL OR reviewer_email IS NOT NULL)
);

CREATE TABLE review_replies (
    reply_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  INTEGER     NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id    INTEGER     NOT NULL REFERENCES users(user_id),
    body       LONGVARCHAR NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_review_replies_body_not_blank CHECK (TRIM(BOTH FROM body) <> '')
);

CREATE TABLE review_likes (
    review_id  INTEGER   NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id    INTEGER   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_review_likes PRIMARY KEY (review_id, user_id)
);

CREATE TABLE review_reply_likes (
    reply_id   INTEGER   NOT NULL REFERENCES review_replies(reply_id) ON DELETE CASCADE,
    user_id    INTEGER   NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_review_reply_likes PRIMARY KEY (reply_id, user_id)
);

CREATE TABLE review_tags (
    tag_id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(80)  NOT NULL UNIQUE,
    label_es   VARCHAR(120) NOT NULL,
    sentiment  VARCHAR(20)  NOT NULL,
    dimension  VARCHAR(80)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_review_tags_sentiment CHECK (sentiment IN ('positive', 'negative', 'neutral'))
);

CREATE TABLE review_tag_assignments (
    review_id INTEGER  NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    tag_id    SMALLINT NOT NULL REFERENCES review_tags(tag_id) ON DELETE CASCADE,
    CONSTRAINT pk_review_tag_assignments PRIMARY KEY (review_id, tag_id)
);

CREATE TABLE brand_requests (
    brand_request_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
    submitter_email      VARCHAR(100),
    name                 VARCHAR(80) NOT NULL,
    comments             LONGVARCHAR,
    status               VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_brand_requests_submitter_identity CHECK (submitted_by_user_id IS NOT NULL OR submitter_email IS NOT NULL),
    CONSTRAINT chk_brand_requests_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE body_type_requests (
    body_type_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by_user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
    submitter_email      VARCHAR(100),
    name                 VARCHAR(50) NOT NULL,
    comments             LONGVARCHAR,
    status               VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_body_type_requests_submitter_identity CHECK (submitted_by_user_id IS NOT NULL OR submitter_email IS NOT NULL),
    CONSTRAINT chk_body_type_requests_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE admin_requests (
    admin_request_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by_user_id INTEGER      NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    submitter_email      VARCHAR(100) NOT NULL,
    motivation           LONGVARCHAR  NOT NULL,
    bio                  LONGVARCHAR,
    justification        LONGVARCHAR,
    status               VARCHAR(20)  NOT NULL DEFAULT 'pending',
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_admin_requests_status CHECK (status IN ('pending', 'approved', 'rejected'))
);
