package ar.edu.itba.paw.persistence;

import ar.edu.itba.paw.model.Community;
import ar.edu.itba.paw.model.CommunityMembershipEntry;
import ar.edu.itba.paw.model.CommunityPost;
import ar.edu.itba.paw.model.CommunityPostComment;
import ar.edu.itba.paw.model.CommunitySearchCriteria;
import ar.edu.itba.paw.model.CommunityTopic;
import ar.edu.itba.paw.model.Page;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.Map;

public interface CommunityDao {
    List<Community> findAll();
    Page<Community> findAll(int page);
    Page<Community> findByCriteria(CommunitySearchCriteria criteria, Long currentUserId);
    Optional<Community> findBySlug(String slug);
    List<CommunityTopic> findAllTopics();
    List<CommunityTopic> findTopicsByIds(Collection<Short> topicIds);
    Community create(long createdByUserId, String slug, String name, String description);
    void updateDetails(long communityId, String name, String description);
    void updateCreatedBy(long communityId, long newOwnerUserId);
    boolean delete(long communityId);
    CommunityPost createPost(long communityId, long authorUserId, String slug, String title, String body);
    CommunityPostComment createComment(long postId, long userId, String body);
    void updatePost(long postId, String title, String body);
    void updateComment(long commentId, String body);
    void replaceTopicAssignments(long communityId, Collection<Short> topicIds);
    void createMembership(long communityId, long userId, String role);
    void deleteMembership(long communityId, long userId);
    Optional<String> findMembershipRole(long communityId, long userId);
    void updateMembershipRole(long communityId, long userId, String newRole);
    List<CommunityMembershipEntry> listMembers(long communityId);
    void setPostHidden(long postId, boolean hidden);
    void setCommentHidden(long commentId, boolean hidden);
    boolean addHelpfulReaction(long postId, long userId);
    boolean removeHelpfulReaction(long postId, long userId);
    boolean isHelpfulReactionAddedByUser(long postId, long userId);
    boolean addCommentHelpfulReaction(long commentId, long userId);
    boolean removeCommentHelpfulReaction(long commentId, long userId);
    boolean isCommentHelpfulReactionAddedByUser(long commentId, long userId);
    Set<Long> findPostHelpfulReactionsByUser(Collection<Long> postIds, long userId);
    Set<Long> findCommentHelpfulReactionsByUser(Collection<Long> commentIds, long userId);
    Map<Long, List<CommunityTopic>> findTopicsByCommunityIds(Collection<Long> communityIds);
    List<CommunityPost> findPostsByCommunityId(long communityId);
    List<CommunityPost> findPostsByIds(Collection<Long> postIds);
    Page<CommunityPost> findVisiblePostsByCommunityId(long communityId, String sort, int page);
    Optional<CommunityPost> findPostByCommunityIdAndSlug(long communityId, String postSlug);
    List<CommunityPostComment> findCommentsByPostId(long postId);
    Optional<CommunityPostComment> findCommentById(long commentId);
    boolean deletePost(long postId);
    boolean deleteComment(long commentId);
    Map<Long, Long> countMembersByCommunityIds(Collection<Long> communityIds);
    Set<Long> findJoinedCommunityIds(long userId, Collection<Long> communityIds);
    Map<Long, Long> countWeeklyPostsByCommunityIds(Collection<Long> communityIds, LocalDateTime since);
    Map<Long, Long> countCommentsByPostIds(Collection<Long> postIds);
    Map<Long, Long> countHelpfulReactionsByPostIds(Collection<Long> postIds);
    Map<Long, Long> countHelpfulReactionsByCommentIds(Collection<Long> commentIds);
}
